<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/11/7 0007
 * Time: 下午 5:08
 */

namespace app\admin\controller;

use think\Controller;

class Base extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $isLogin = $this->isLogin();
        if(!$isLogin){
            return $this->redirect('Login/index');
        }
    }

    public function isLogin(){
        $user = session(config('admin.session_user'),'',config('admin.session_user_scope'));
        if($user && $user->id){
            return true;
        }else{
            return false;
        }

    }
}